*** Variables ***
${CAMPO_PRIMEIRO_NUMERO}        id=android_field_first_number
${CAMPO_SEGUNDO_NUMERO}         id=android_field_second_number
${BOTAO_SOMAR}                  id=android_button_sum
${BOTAO_SUBTRAIR}               id=android_button_sub
${BOTAO_MULTIPLICAR}            id=android_button_mult
${BOTAO_DIVIDIR}                id=android_button_div
${RESULTADO}                    id=android_result_text