name: Execute Mobile Test on BrowserStack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python 3.12
        uses: actions/setup-python@v3
        with:
          python-version: "3.12"

      - name: Update system certificates
        run: |
          sudo apt-get update
          sudo apt-get install -y ca-certificates
          sudo update-ca-certificates

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install certifi
          pip install -r requirements.txt

      - name: Install Appium and drivers
        run: |
          npm install -g appium
          appium driver install uiautomator2
          appium driver install xcuitest

      - name: Set SSL_CERT_FILE
        run: |
          echo "SSL_CERT_FILE=$(python -c 'import certifi; print(certifi.where())')" >> $GITHUB_ENV

      - name: Start Appium
        run: |
          appium --log-level info &

      - name: Verificar Certificado
        run: |
          echo "Certificado em uso:"
          python -c 'import certifi; print(certifi.where())'
          cat $(python -c 'import certifi; print(certifi.where())')

      - name: Executar teste no BrowserStack
        env:
          SSL_CERT_FILE: ${{ env.SSL_CERT_FILE }}
          BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}
          BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
        run: |
          export SSL_CERT_FILE=$SSL_CERT_FILE
          echo "Using SSL_CERT_FILE=$SSL_CERT_FILE"
          robot features/Somar.robot
