name: Execute Mobile Test on BrowserStack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          robot features/Somar.robot
#      - name: Upload do APK
#        run: |
#          curl -u "marceloribelato_ksi0ah:Eej2sRzekpDZaBDLJGKr" \
#          -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/module-app" \
#          -F file=@app/Calculadora.apk

#      - name: Executar teste no BrowserStack
#        run: |
#          curl -u "marceloribelato_ksi0ah:Eej2sRzekpDZaBDLJGKr" \
#          -X POST "https://api-cloud.browserstack.com/app-automate/upload" \
#          -d '{"testSuite": "bs://7e756739686269e67a25e02bf170a2d9360344a0", "devices": ["Samsung Galaxy S24 Ultra-14.0"]}' \
#          -H "Content-Type: application/json"
