name: Execute Mobile Test on BrowserStack
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"

#      - name: Upload do APK
#        run: |
#          curl -u "marceloribelato_ksi0ah:Eej2sRzekpDZaBDLJGKr" \
#          -X POST "https://api-cloud.browserstack.com/app-automate/espresso/v2/module-app" \
#          -F file=@app/Calculadora.apk

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install --force-reinstall "Appium-Python-Client<4.0.0"
           

      - name: Executar teste no BrowserStack
        run: |  
          robot features/Somar.robot 
          

